config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'profil', to: 'pages#profil', as: 'profil'
  get 'friends_list', to: 'pages#friends_list', as: 'friends'
  get 'settings', to: 'pages#settings', as: 'settings'

  resources :books, only: %i[show] do
    resources :user_books, only: %i[create update destroy] do
      post :archive
    end
    resources :reviews, only: %i[new create]
    collection do
      get :search
      get :reading_list
      get :wish_list
      get :read_list
    end
  end

  resources :users, only: %i[show] do
    resources :friendships, only: %i[create]
  end

  resources :friendships, only: %i[update destroy] do
    member do
      patch :reject
    end
  end
end

app/views/shared/_darkmode_toggle.html.erb
<button
  id="app-darkmode-toggle"
  type="button"
  data-dark-mode-target="themeToggle"
  data-action="click->dark-mode#toggleTheme"
>
  <svg
    class="w-6 h-6 hidden hover:text-sky-500"
    fill="currentColor"
    viewBox="0 0 20 20"
    xmlns="http://www.w3.org/2000/svg"
    data-dark-mode-target="darkIcon"
  >
    <path
      d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"
    ></path>
  </svg>

  <svg
    class="w-6 h-6 hidden hover:text-sky-600"
    fill="currentColor"
    viewBox="0 0 20 20"
    xmlns="http://www.w3.org/2000/svg"
    data-dark-mode-target="lightIcon"
  >
    <path
      d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
      fill-rule="evenodd"
      clip-rule="evenodd"
    ></path>
  </svg>

</button>

app/views/shared/_flashes.html.erb
<!-- A refaire avec Tailwind puis ajouter dans application.html.erb render "shared/flashes" -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer h-24 w-full bg-sky-500 dark:bg-sky-800 fixed bottom-0">

</footer>

app/views/shared/_navbar.html.erb
<nav class="text-slate-900 dark:text-white flex justify-between items-center pt-6 pb-6 pr-12 pl-12">
  <div>LOGO</div>

  <!-- Barre de navigation quand l'utilisateur est connecté -->
  <% if user_signed_in? %>

    <div class="search shrink w-2/4">
      <%= form_with url: search_books_path, remote: true, method: :get do %>

        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"      stroke="currentColor" class="w-6 h-6 absolute m-2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
        </svg>

        <%= text_field_tag :query,
          params[:query],
          class: "w-full rounded focus:outline-none focus:ring-0 focus:border-sky-500 border-2 focus:animate-pulse dark:text-slate-900",
          placeholder: "       Rechercher un livre, un auteur ...",
          name: "query"
        %>
      <% end %>
    </div>

    <div class="flex items-center">
      <a class="hover:text-sky-600 dark:hover:text-sky-500 mr-6" href="/dashboard">Mon Tableau de bord</a>


    <div data-controller="dropdown" class="relative group">
      <a class="hover:text-sky-600 dark:hover:text-sky-500 mr-6 pb-9" href="#" data-action="mouseenter->dropdown#show mouseleave->dropdown#hide">
        Mes Bibliothèques
      </a>
      <div data-dropdown-target="link" class="hidden absolute left-0 mt-2 w-48 z-10 group-hover:block border-l border-sky-500 origin-top-left transform scale-0 group-hover:scale-100 transition-transform duration-300">
        <!-- sous-menu -->
        <a class="block px-4 py-2 hover:text-sky-500" href="/books/wish_list">Liste de souhait</a>
        <a class="block px-4 py-2 hover:text-sky-500 " href="/books/reading_list">Liste en cours</a>
        <a class="block px-4 py-2 hover:text-sky-500 " href="/books/read_list">Liste lus</a>
      </div>
    </div>
    <div data-controller="dropdown" class="relative group">
      <a class="hover:text-sky-600 dark:hover:text-sky-500 mr-6 pb-9" href="#" data-action="mouseenter->dropdown#show mouseleave->dropdown#hide">
        Mon Profil
      </a>
      <div data-dropdown-target="link" class="hidden absolute left-0 mt-2 w-48 z-10 group-hover:block border-l border-sky-500 origin-top-left transform scale-0 group-hover:scale-100 transition-transform duration-300">
        <!-- sous-menu -->
        <a class="block px-4 py-2 hover:text-sky-500" href="/profil">Mon Profil</a>
        <a class="block px-4 py-2 hover:text-sky-500" href="/friends_list">Mes Amis</a>
        <a class="block px-4 py-2 hover:text-sky-500" href="/settings">Paramètres</a>
        <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class:"block px-4 py-2 hover:text-sky-500" %>
      </div>
    </div>
      <span class="pt-1"><%= render "shared/darkmode_toggle"%></span>
    </div>
  <% else %>
  <!-- Barre de navigation quand l'utilisateur n'est pas connecté -->
  <div class="flex items-center">
    <a class="hover:text-sky-600 dark:hover:text-sky-500 mr-4" href="/users/sign_up" role="button">S'Enregistrer</a>
    <a class="hover:text-sky-600 dark:hover:text-sky-500 mr-4" href="/users/sign_in" role="button">Se Connecter</a>
    <span class="pt-1"><%= render "shared/darkmode_toggle"%></span>
  </div>
  <% end %>
</nav>

app/views/shared/_star.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-sky-500 fill-sky-500 inline-block">
  <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
</svg>

app/views/shared/_star_empty.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-slate-800 dark:text-slate-200 inline-block">
  <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
</svg>