config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'profil', to: 'pages#profil', as: 'profil'
  get 'friends_list', to: 'pages#friends_list', as: 'friends'
  get 'settings', to: 'pages#settings', as: 'settings'

  resources :books, only: %i[show] do
    resources :user_books, only: %i[create update destroy] do
      post :archive
    end
    resources :reviews, only: %i[new create]
    collection do
      get :search
      get :reading_list
      get :wish_list
      get :read_list
    end
  end

  resources :users, only: %i[show] do
    resources :friendships, only: %i[create]
  end

  resources :friendships, only: %i[update destroy] do
    member do
      patch :reject
    end
  end
end

app/views/pages/friends_list.html.erb
<h2>Demande en attente : </h2>
<ul>
  <% @friendship_pending.each do |friendship| %>
    <li>
      <%= friendship.user.user_name  %>
      <%= link_to "Accepter", friendship_path(friendship), data: {turbo_method: :patch}%> |
      <%= link_to "Rejeter", reject_friendship_path(friendship), data: {turbo_method: :patch}%>
    </li>
  <% end %>
</ul>


<h2>Mes Amis :</h2>
<ul>
  <% @friends.each do |friend| %>
    <li><%= friend.user_name %></li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<div class="container mx-auto flex home">

  <div class="justify-center text-center">
    <h1 class="text-6xl text-sky-500 text-center font-bold p-8 mt-24">NOMSUPERAPP</h1>
      <div class="slider-container slider-1 max-w-xl overflow-hidden">
        <div class="slider flex">
          <p class="shrink-0 w-full text-center py-8 text-lg text-slate-700 dark:text-slate-200">Envie de <span class="text-slate-900 dark:text-slate-50 font-semibold">Rejoindre</span> le plus grand club de lecture ?</p>
          <p class="shrink-0 w-full text-center py-8 text-lg text-slate-700 dark:text-slate-200">Partage tes lectures avec tes <span class="text-slate-900 dark:text-slate-50  font-semibold">amis</span> !</p>
          <p class="shrink-0 w-full text-center py-8 text-lg text-slate-700 dark:text-slate-200">Découvre quels sont les livres les plus <span class="text-slate-900 dark:text-slate-50  font-semibold">populaires</span> du moment !</p>
          <p class="shrink-0 w-full text-center py-8 text-lg text-slate-700 dark:text-slate-200">Garde un <span class="text-slate-900 dark:text-slate-50 font-semibold">historique</span> de tes lectures !</p>
        </div>
      </div>
      <div>
        <a class="mt-10 bg-sky-400 px-6 py-3 min-w-[160px] rounded-lg hover:cursor-pointer hover:bg-sky-300 inline-block text-center motion-safe:animate-bounce"  href="/users/sign_up" role="button">Rejoindre</a>
      </div>
  </div>

  <div class="w-4/6 max-h-60">
    <%= image_tag "IllustrationHome.png", class:"home-img"%>
  </div>

</div>

  <%= render "shared/footer" %>