config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'profil', to: 'pages#profil', as: 'profil'
  get 'friends_list', to: 'pages#friends_list', as: 'friends'
  get 'settings', to: 'pages#settings', as: 'settings'

  resources :books, only: %i[show] do
    resources :user_books, only: %i[create update destroy] do
      post :archive
    end
    resources :reviews, only: %i[new create]
    collection do
      get :search
      get :reading_list
      get :wish_list
      get :read_list
    end
  end

  resources :users, only: %i[show] do
    resources :friendships, only: %i[create]
  end

  resources :friendships, only: %i[update destroy] do
    member do
      patch :reject
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :user_books
  has_many :users, through: :user_books
  has_many :reviews

  # enum :status, { wished: 0, pending: 1, read: 2, archive: 3 }

  validates :isbn, uniqueness: true

  def average_rating
    total_rating = reviews.sum { |review| review.rating.to_f }
    valid_reviews_count = reviews.count { |review| !review.rating.nil? }

    return total_rating / valid_reviews_count if valid_reviews_count.positive?

    0.0
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show]
  before_action :set_user_book, only: %i[wish_list reading_list read_list]

  def show
    @reviews = @book.reviews
    @user_book = UserBook.find_by(user: current_user, book_id: @book.id)
  end

  def wish_list
    @wish_list = books_from_status(@user_books, 0)
  end

  def reading_list
    @reading_list = books_from_status(@user_books, 1)
  end

  def read_list
    @read_list = books_from_status(@user_books, 2)
  end

  def search
    return unless params[:query].present?

    search_with_title
    search_with_author
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def set_user_book
    @user_books = current_user.user_books
  end

  def book_params
    params.require(:book).permit(:title, :author, :description, :score, :isbn, :cover_img_url)
  end

  def books_from_status(user_books, status)
    user_books.where(status: status).map(&:book)
  end

  def search_with_title
    @search_books_title = []
    GoogleBooks.search("intitle:#{params[:query]}", count: 10, country: "fr").each do |book|
      next unless valid_book?(book)

      add_book_in_db(book)
    end

    @search_books_title = Book.where('LOWER(title) LIKE ?', "%#{params[:query].downcase}%")
  end

  def search_with_author
    @search_books_author = []
    GoogleBooks.search("inauthor:#{params[:query]}", count: 10, country: "fr").each do |book|
      next unless valid_book?(book)

      add_book_in_db(book)
    end

    @search_books_author = Book.where('LOWER(author) LIKE ?', "%#{params[:query].downcase}%")
  end

  def valid_book?(book)
    return false if book.language != 'fr' && book.isbn.nil?
    return false unless Book.find_by(isbn: book.isbn.to_s).nil?
    return true if book.image_link.present?

    add_img_book(book)
    false
  end

  def add_book_in_db(book)
    new_book = build_book_from_google_book(book)
    new_book.save
  end

  def add_img_book(book)
    image = Openlibrary::Covers::Image.new(book.isbn.to_s)
    return unless image.found?

    new_book = build_book_from_google_book(book, image.url)
    new_book.save
  end

  def build_book_from_google_book(book, img_url = nil)
    Book.new(
      title: book.title.truncate(100),
      description: book.description,
      author: book.authors,
      cover_img_url: img_url || book.image_link,
      isbn: book.isbn,
      score: rand(10...100)
    )
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/read_list.html.erb
<div class="container mx-auto mt-8 mb-20">

<!-- La recherche ne retourne aucun résultat  :-->
  <% if @read_list.length == 0 %>
    <p class="mx-auto text-center">Vous n'avez aucun livre dans votre liste de lecture ...</p>

<!-- Affichage des résultats :-->
  <% else %>
    <h1 class="mb-8 text-lg">Liste de tous les livres que vous avez lus :</h1>
    <div class="grid grid-cols-1 md:grid-cols-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-6 justify-center text-center">
    <% @read_list.each do |book| %>
      <div>
        <%= link_to book_path(book) do %>
          <img src="<%= book.cover_img_url %>", class="mx-auto w-64 h-80 hover:animate-pulse rounded-r-lg dark:border-slate-200 border">
          <%= book.title %>
        <% end %>
      </div>
    <% end %>
    </div>
  <% end %>

</div>

app/views/books/reading_list.html.erb
<div class="container mx-auto mt-8 mb-20">

<!-- La recherche ne retourne aucun résultat  :-->
  <% if @reading_list.length == 0 %>
    <p class="mx-auto text-center">Vous n'avez aucun livre en cours de lecture dans votre liste ...</p>

<!-- Affichage des résultats :-->
  <% else %>
    <h1 class="mb-8 text-lg">Liste de tous les livres que vous êtes en train de lire :</h1>
    <div class="grid grid-cols-1 md:grid-cols-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-6 justify-center text-center">
    <% @reading_list.each do |book| %>
      <div>
        <%= link_to book_path(book) do %>
          <img src="<%= book.cover_img_url %>", class="mx-auto w-64 h-80 hover:animate-pulse rounded-r-lg dark:border-slate-200 border">
          <%= book.title %>
        <% end %>
      </div>
    <% end %>
    </div>
  <% end %>

</div>

app/views/books/search.html.erb
<div class="container mx-auto mt-8 mb-20">
  <h1 class="mb-8 text-lg">Ajouter un livre à votre bibliothèque :</h1>

<!-- La recherche ne retourne aucun résultat  :-->
  <% if @search_books_author.length == 0 && @search_books_title.length == 0%>
    <p class="mx-auto text-center">Aucun livre ne correspond à votre recherche ...</p>
  <% end %>

<!-- Affichage des résultats :-->
  <div class="grid grid-cols-1 md:grid-cols-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-6 justify-center text-center">
    <% if @search_books_author %>
      <% @search_books_author.each do |book| %>
          <div>
            <%= link_to book_path(book) do %>
              <img src="<%= book.cover_img_url %>", class="mx-auto w-64 h-80 hover:animate-pulse rounded-r-lg dark:border-slate-200 border">
              <%= book.title %>
            <% end %>
          </div>
      <% end %>
    <% end %>

    <% if @search_books_title %>
      <% @search_books_title.each do |book| %>
        <ul>
          <li>
            <%= link_to book_path(book) do %>
              <img src="<%= book.cover_img_url %>", class="mx-auto w-64 h-80 hover:animate-pulse rounded-r-lg dark:border-slate-200 border">
              <%= book.title %>
            <% end %>
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>


</div>

app/views/books/show.html.erb
<div class="container mx-auto mt-8 mb-20">

  <div class="flex">
      <div class="basis-1/2">
        <img src="<%= @book.cover_img_url %>" class="mx-auto w-6/12 rounded-r-lg dark:border-slate-200 border">
      </div>

      <div class="basis-1/2">
        <div class="flex justify-between">
          <div>
            <h1 class="text-xl text-sky-400 font-semibold"><%= @book.title %></h1>
            <h2 class="font-semibold">De : <%= @book.author %></h2>
          </div>
          <div>
            <p>
              <% 5.times do |i| %>
                <% if i < @book.average_rating.floor %>
                  <%= render "shared/star"%>
                <% else %>
                  <%= render "shared/star_empty"%>
                <% end %>
              <% end %>
            </p>
            <p class="text-end font-semibold text-sm">(<%= @book.reviews.length%> notes)</p>
          </div>

        </div>
        <div class="border-2 border-sky-400 p-12 mt-6 bg-slate-100 dark:bg-slate-800 dark:border-sky-500 rounded">
          <p class="text-right font-semibold text-sm mb-8"><%= @book.score %> pts</p>
          <p class="text-slate-800 dark:text-slate-200 text-justify"><%= @book.description %></p>
        </div>
        <div class="m-9 flex justify-between">
          <!-- Bouttons pour ajouter les livres aux différentes listes-->
          <% if  @user_book.nil? %>
            <%= button_to "Ajouter à ma liste de souhaits", book_user_books_path(@book), method: :post, params: { status: 0 }, class:"bg-sky-400 px-4 py-2 min-w-[125px] rounded hover:cursor-pointer hover:bg-sky-300" %>
          <% end %>

          <% if !@user_book.nil? && @user_book.status == 1 %>
            <%= link_to "Ajouter à ma liste de livres terminés", book_user_book_path(@book), data: {turbo_method: :patch}, class:"bg-sky-400 px-4 py-2 min-w-[125px] rounded hover:cursor-pointer hover:bg-sky-300" %>
          <% end %>

          <% unless !@user_book.nil? && @user_book.status >= 1  %>
            <%= button_to "Ajouter à ma liste de lecture", book_user_books_path(@book), method: :post, params: { status: 1 }, class:"bg-sky-400 px-4 py-2 min-w-[125px] rounded hover:cursor-pointer hover:bg-sky-300"%>
          <% end %>

          <% if !@user_book.nil? && @user_book.status != 2 %>
            <%= button_to "Supprimer le livre", book_user_books_path(@book, @user_book), form: {
                            data: { turbo_method: :delete, turbo_confirm: "Really?!?" }
                      }, class:"bg-sky-400 px-4 py-2 min-w-[125px] rounded hover:cursor-pointer hover:bg-sky-300"%>
          <% end %>

          <% if !@user_book.nil? && @user_book.status == 2 %>
            <%= button_to "Archiver le livre", book_user_book_archive_path(@book, @user_book), method: :post, class:"bg-sky-400 px-4 py-2 min-w-[125px] rounded hover:cursor-pointer hover:bg-sky-300" %>
          <% end %>
        </div>
      </div>
  </div>

  <!-- todo Masquer le formulaire des reviews si l'utilisateur n'a pas le livre au moins sa liste en cours -->
  <%= render 'reviews/form' %>
  <div class="mt-6">
    <% @book.reviews.each do |review| %>
      <div class="mb-3 p-6 border-sky-500 bg-slate-50 dark:bg-slate-700">
        <p>Par <span class="font-semibold text-sky-400 dark:text-sky-500"><%= review.user.user_name%> </span>(<%= review.rating %><%= render "shared/star"%>) : <br> <span class="text-slate-800 dark:text-slate-200" ><%= review.content %></span></p>
      </div>
    <% end %>
  </div>
</div>

app/views/books/wish_list.html.erb
<div class="container mx-auto mt-8 mb-20">

<!-- La recherche ne retourne aucun résultat  :-->
  <% if @wish_list.length == 0 %>
    <p class="mx-auto text-center">Vous n'avez aucun livre dans votre liste de souhaits ...</p>

<!-- Affichage des résultats :-->
  <% else %>
    <h1 class="mb-8 text-lg">Liste de tous les livres dans votre liste de souhaits :</h1>
    <div class="grid grid-cols-1 md:grid-cols-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-6 justify-center text-center">
    <% @wish_list.each do |book| %>
      <div>
        <%= link_to book_path(book) do %>
          <img src="<%= book.cover_img_url %>", class="mx-auto w-64 h-80 hover:animate-pulse rounded-r-lg dark:border-slate-200 border">
          <%= book.title %>
        <% end %>
      </div>
    <% end %>
    </div>
  <% end %>

</div>