config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'profil', to: 'pages#profil', as: 'profil'
  get 'friends_list', to: 'pages#friends_list', as: 'friends'
  get 'settings', to: 'pages#settings', as: 'settings'

  resources :books, only: %i[show] do
    resources :user_books, only: %i[create update destroy] do
      post :archive
    end
    resources :reviews, only: %i[new create]
    collection do
      get :search
      get :reading_list
      get :wish_list
      get :read_list
    end
  end

  resources :users, only: %i[show] do
    resources :friendships, only: %i[create]
  end

  resources :friendships, only: %i[update destroy] do
    member do
      patch :reject
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book = @book
    @review.user = current_user
    if @review.save
      redirect_to @book, notice: 'Commentaire ajouté avec succès.'
    else
      flash.now[:alert] = 'Erreur lors de l\'ajout du commentaire.'
      render 'books/show'
    end
  end

  private

  def find_book
    @book = Book.find(params[:book_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class="mt-12 border-t p-6 border-sky-500 bg-slate-50 dark:bg-slate-700">
  <%= form_with(model: [ @book, Review.new ], url: book_reviews_path(@book)) do |form| %>
    <div class="field mt-2">
    <%= form.label :rating, 'Note', class:"hidden" %>
      <!-- TODO changer les radio button par des étoiles -->
      <div>
        <% (1..5).each do |rating| %>
          <%= form.radio_button :rating, rating %>
        <% end %>
      </div>
    </div>

    <div class="field mt-2">
      <%= form.label :content, 'Votre commentaire' %>
      <%= form.text_area :content, class:"rounded w-full p-1 mt-2 focus:outline-none focus:ring-0 focus:border-sky-500 border-2 text-slate-900" %>
    </div>

    <div class="actions">
      <%= form.submit 'Ajouter', class:"bg-sky-400 px-4 py-2 min-w-[125px] rounded hover:cursor-pointer hover:bg-sky-300"  %>
    </div>
  <% end %>
</div>